---
output:
  word_document: default
  html_document: default
---
# Project Phase 1

## Team Rafalowski-Rabil

### Exploratory Data Anlysis

#### Load Libraries
```{r load libraries, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(tidymodels)
library(mice) #package for imputation
library(VIM) #visualizing missingness
library(ranger) #for random forests
library(randomForest) #also for random forests
library(naniar) #visualizing missingness
library(caret)
library(skimr)
library(GGally)
library(gridExtra)
library(vip) #variable importance
library(stringr)
library(rsconnect)
```

#### Setup______________________________________________________________________

# Load and Clean Data
```{r clean and tidy data, include=FALSE}
#Read in Data set
sharkstudent <- read_csv("shark_student.csv")

#Create New Season Variable
sharkstudent<- mutate(sharkstudent,"Season" = str_sub(sharkstudent$SeasonEpisode,12,14))

# Renames columns without spaces and slash
colnames(sharkstudent)[colnames(sharkstudent) == "Health / Wellness"] <- "HealthWellness"
colnames(sharkstudent)[colnames(sharkstudent) == "Lifestyle / Home"] <- "LifestyleHome" 
colnames(sharkstudent)[colnames(sharkstudent) == "Software / Tech"] <- "SoftwareTech" 
colnames(sharkstudent)[colnames(sharkstudent) == "Children / Education"] <- "ChildrenEducation" 
colnames(sharkstudent)[colnames(sharkstudent) == "Fashion / Beauty"] <- "FashionBeauty"
colnames(sharkstudent)[colnames(sharkstudent) == "Media / Entertainment"] <- "MediaEntertainment"
colnames(sharkstudent)[colnames(sharkstudent) == "Fitness / Sports / Outdoors"] <- "FitnessSportsOutdoors"
colnames(sharkstudent)[colnames(sharkstudent) == "Green/CleanTech"] <- "GreenCleanTech"
colnames(sharkstudent)[colnames(sharkstudent) == "Uncertain / Other"] <- "UncertainOther"
colnames(sharkstudent)[colnames(sharkstudent) == "Food and Beverage"] <- "FoodBeverage"
colnames(sharkstudent)[colnames(sharkstudent) == "Business Services"] <- "BusinessServices"
colnames(sharkstudent)[colnames(sharkstudent) == "Pet Products"] <- "PetProducts"

#Convert all character variables to Factor
sharkstudent = sharkstudent %>% mutate_if(is.character,as_factor)

#Concert to factor and recode categories
sharkstudent <- sharkstudent %>% 
  mutate(ReceiveOffer = as_factor(ReceiveOffer)) %>%
  mutate(ReceiveOffer = fct_recode(ReceiveOffer, "Yes" = "1", "No" = "0")) %>%
  mutate(RejectOffer = as_factor(RejectOffer)) %>%
  mutate(RejectOffer = fct_recode(RejectOffer, "Yes" = "1", "No" = "0")) %>%
  mutate(Deal_Yes = as_factor(Deal_Yes)) %>%
  mutate(Deal_Yes = fct_recode(Deal_Yes, "Yes" = "1", "No" = "0")) %>%
  mutate(Deal_No = as_factor(Deal_No)) %>%
  mutate(Deal_No = fct_recode(Deal_No, "Yes" = "1", "No" = "0")) %>%
  mutate(Eth1 = as_factor(Eth1)) %>%
  mutate(Eth1 = fct_recode(Eth1, "African American" = "1", "White" = "2", "Asian" = "3", "Latino" = "4", "No presenter 1" = "0")) %>%
  mutate(Eth2 = as_factor(Eth2)) %>%
  mutate(Eth2 = fct_recode(Eth2, "African American" = "1", "White" = "2", "Asian" = "3", "Latino" = "4", "No presenter 2" = "0")) %>%
  mutate(Eth3 = as_factor(Eth3)) %>%
  mutate(Eth3 = fct_recode(Eth3, "African American" = "1", "White" = "2", "Asian" = "3", "Latino" = "4", "No presenter 3" = "0")) %>%
  mutate(Eth4 = as_factor(Eth4)) %>%
  mutate(Eth4 = fct_recode(Eth4, "African American" = "1", "White" = "2", "Asian" = "3", "Latino" = "4", "No presenter 4" = "0")) %>%
  mutate(Eth5 = as_factor(Eth5)) %>%
  mutate(Eth5 = fct_recode(Eth5, "African American" = "1", "White" = "2", "Asian" = "3", "Latino" = "4", "No presenter 5" = "0")) %>%
  mutate(Male1 = as_factor(Male1)) %>%
  mutate(Male1 = fct_recode(Male1, "Yes" = "1", "No" = "0")) %>%
  mutate(Male2 = as_factor(Male2)) %>%  
  mutate(Male2 = fct_recode(Male2, "Yes" = "1", "No" = "0")) %>%
  mutate(Male3 = as_factor(Male3)) %>%
  mutate(Male3 = fct_recode(Male3, "Yes" = "1", "No" = "0")) %>%
  mutate(Male4 = as_factor(Male4)) %>%
  mutate(Male4 = fct_recode(Male4, "Yes" = "1", "No" = "0")) %>%
  mutate(Female1 = as_factor(Female1)) %>%
  mutate(Female1 = fct_recode(Female1, "Yes" = "1", "No" = "0")) %>%
  mutate(Female2 = as_factor(Female2)) %>%
  mutate(Female2 = fct_recode(Female2, "Yes" = "1", "No" = "0")) %>%
  mutate(Female3 = as_factor(Female3)) %>%
  mutate(Female3 = fct_recode(Female3, "Yes" = "1", "No" = "0")) %>%
  mutate(Female4 = as_factor(Female4)) %>%
  mutate(Female4 = fct_recode(Female4, "Yes" = "1", "No" = "0")) %>%
  mutate(Novelties = as_factor(Novelties)) %>% 
  mutate(Novelties = fct_recode(Novelties, "Yes" = "1", "No" = "0" )) %>%
  mutate(`HealthWellness` = as_factor(`HealthWellness`)) %>% 
  mutate(`HealthWellness` = fct_recode(`HealthWellness`, "Yes" = "1", "No" = "0" )) %>%
  mutate(`FoodBeverage` = as_factor(`FoodBeverage`)) %>% 
  mutate(`FoodBeverage` = fct_recode(`FoodBeverage`, "Yes" = "1", "No" = "0" )) %>%
  mutate(`BusinessServices` = as_factor(`BusinessServices`)) %>% 
  mutate(`BusinessServices` = fct_recode(`BusinessServices`, "Yes" = "1", "No" = "0" )) %>%
  mutate(`LifestyleHome` = as_factor(`LifestyleHome`)) %>% 
  mutate(`LifestyleHome` = fct_recode(`LifestyleHome`, "Yes" = "1", "No" = "0" )) %>%
  mutate(`SoftwareTech` = as_factor(`SoftwareTech`)) %>% 
  mutate(`SoftwareTech` = fct_recode(`SoftwareTech`, "Yes" = "1", "No" = "0" )) %>%
  mutate(`ChildrenEducation` = as_factor(`ChildrenEducation`)) %>% 
  mutate(`ChildrenEducation` = fct_recode(`ChildrenEducation`, "Yes" = "1", "No" = "0" )) %>%
  mutate(Automotive = as_factor(Automotive)) %>% 
  mutate(Automotive = fct_recode(Automotive, "Yes" = "1", "No" = "0" )) %>%
  mutate(`FashionBeauty` = as_factor(`FashionBeauty`)) %>% 
  mutate(`FashionBeauty` = fct_recode(`FashionBeauty`, "Yes" = "1", "No" = "0" )) %>%
  mutate(`MediaEntertainment` = as_factor(`MediaEntertainment`)) %>% 
  mutate(`MediaEntertainment` = fct_recode(`MediaEntertainment`, "Yes" = "1", "No" = "0" )) %>%
  mutate(`FitnessSportsOutdoors` = as_factor(`FitnessSportsOutdoors`)) %>% 
  mutate(`FitnessSportsOutdoors` = fct_recode(`FitnessSportsOutdoors`, "Yes" = "1", "No" = "0" )) %>%
  mutate(`PetProducts` = as_factor(`PetProducts`)) %>% 
  mutate(`PetProducts` = fct_recode(`PetProducts`, "Yes" = "1", "No" = "0" )) %>%
  mutate(Travel = as_factor(Travel)) %>% 
  mutate(Travel = fct_recode(Travel, "Yes" = "1", "No" = "0" )) %>%
  mutate(`GreenCleanTech` = as_factor(`GreenCleanTech`)) %>% 
  mutate(`GreenCleanTech` = fct_recode(`GreenCleanTech`, "Yes" = "1", "No" = "0" )) %>%
  mutate(`UncertainOther` = as_factor(`UncertainOther`)) %>% 
  mutate(`UncertainOther` = fct_recode(`UncertainOther`, "Yes" = "1", "No" = "0" )) %>%
  mutate(MalePresenter = as_factor(MalePresenter)) %>% 
  mutate(MalePresenter = fct_recode(MalePresenter, "Yes" = "1", "No" = "0" )) %>%
  mutate(FemalePresenter = as_factor(FemalePresenter)) %>% 
  mutate(FemalePresenter = fct_recode(FemalePresenter, "Yes" = "1", "No" = "0" )) %>%
  mutate(MixedGenderPresenters = as_factor(MixedGenderPresenters)) %>% 
  mutate(MixedGenderPresenters = fct_recode(MixedGenderPresenters, "Yes" = "1", "No" = "0" )) %>%
  mutate(CompanyState = as_factor(CompanyState)) %>% 
  mutate(CompanyState = fct_recode(CompanyState, "Yes" = "1", "No" = "0" )) %>%
  mutate(BarbaraCorcoran = as_factor(BarbaraCorcoran)) %>% 
  mutate(BarbaraCorcoran = fct_recode(BarbaraCorcoran, "Yes" = "1", "No" = "0" )) %>%
  mutate(MarkCuban = as_factor(MarkCuban)) %>% 
  mutate(MarkCuban = fct_recode(MarkCuban, "Yes" = "1", "No" = "0" )) %>%
  mutate(LoriGreiner = as_factor(LoriGreiner)) %>% 
  mutate(LoriGreiner = fct_recode(LoriGreiner, "Yes" = "1", "No" = "0" )) %>%
  mutate(RobertHerjavec = as_factor(RobertHerjavec)) %>% 
  mutate(RobertHerjavec = fct_recode(RobertHerjavec, "Yes" = "1", "No" = "0" )) %>%
  mutate(DaymondJohn = as_factor(DaymondJohn)) %>% 
  mutate(DaymondJohn = fct_recode(DaymondJohn, "Yes" = "1", "No" = "0" )) %>%
  mutate(KevinOLeary = as_factor(KevinOLeary)) %>% 
  mutate(KevinOLeary = fct_recode(KevinOLeary, "Yes" = "1", "No" = "0" )) %>%
  mutate(KevinHarrington = as_factor(KevinHarrington)) %>% 
  mutate(KevinHarrington = fct_recode(KevinHarrington, "Yes" = "1", "No" = "0" )) %>%
  mutate(Guest = as_factor(Guest)) %>% 
  mutate(Guest = fct_recode(Guest, "Yes" = "1", "No" = "0" ))

# Remove weak or non-required variables
sharkstudent = sharkstudent %>% select(-CompanyState) 
sharkstudent = sharkstudent %>% select(-Deal_No) 
sharkstudent = sharkstudent %>% select(-ReceiveOffer)
sharkstudent = sharkstudent %>% select(-RejectOffer)
sharkstudent = sharkstudent %>% select(-Male4)
# sharkstudent = sharkstudent %>% select(-Female4)
# sharkstudent = sharkstudent %>% select(-Eth4)
# sharkstudent = sharkstudent %>% select(-Eth5)
sharkstudent = sharkstudent %>% select(-SeasonEpisode)
sharkstudent = sharkstudent %>% select(-Company)
sharkstudent = sharkstudent %>% select(-X1)  
```

#### Summary
```{r Summary and output}
str(sharkstudent)
summary(sharkstudent)
```


#### Visualizations______________________________________________________________________

```{r Group 1 Visualizations}
ggplot(sharkstudent, aes(x = Season, fill = Deal_Yes)) + geom_bar(position = "fill") + theme(axis.text.x = element_text(angle =60))
```

```{r Group 2 Visualizations}
p1 = ggplot(sharkstudent, aes(x = Eth1, fill = Deal_Yes)) + geom_bar(position = "fill") + theme(axis.text.x = element_text(angle =60))               
p2 = ggplot(sharkstudent, aes(x = Eth2, fill = Deal_Yes)) + geom_bar(position = "fill") + theme(axis.text.x = element_text(angle =60))     
p3 = ggplot(sharkstudent, aes(x = Eth3, fill = Deal_Yes)) + geom_bar(position = "fill") + theme(axis.text.x = element_text(angle =60))       
p4 = ggplot(sharkstudent, aes(x = Eth4, fill = Deal_Yes)) + geom_bar(position = "fill") + theme(axis.text.x = element_text(angle =60))       
grid.arrange(p1,p2,p3,p4,ncol=2)
```

```{r Group 3 Visualizations}
p1 = ggplot(sharkstudent, aes(x = Male1, fill = Deal_Yes)) + geom_bar(position = "fill") + theme(axis.text.x = element_text(angle =60))               
p2 = ggplot(sharkstudent, aes(x = Male2, fill = Deal_Yes)) + geom_bar(position = "fill") + theme(axis.text.x = element_text(angle =60))     
p3 = ggplot(sharkstudent, aes(x = Male3, fill = Deal_Yes)) + geom_bar(position = "fill") + theme(axis.text.x = element_text(angle =60))
grid.arrange(p1,p2,p3, ncol=2)
```

```{r Group 4 Visualizations}
p1 = ggplot(sharkstudent, aes(x = Female1, fill = Deal_Yes)) + geom_bar(position = "fill") + theme(axis.text.x = element_text(angle =60))               
p2 = ggplot(sharkstudent, aes(x = Female2, fill = Deal_Yes)) + geom_bar(position = "fill") + theme(axis.text.x = element_text(angle =60))     
p3 = ggplot(sharkstudent, aes(x = Female3, fill = Deal_Yes)) + geom_bar(position = "fill") + theme(axis.text.x = element_text(angle =60))
grid.arrange(p1,p2,p3, ncol=2)
```

```{r Group 5 Visualizations}
p1 = ggplot(sharkstudent, aes(x = Novelties, fill = Deal_Yes)) + geom_bar(position = "fill")
p2 = ggplot(sharkstudent, aes(x = `HealthWellness`, fill = Deal_Yes)) + geom_bar(position = "fill")
p3 = ggplot(sharkstudent, aes(x = `FoodBeverage`, fill = Deal_Yes)) + geom_bar(position = "fill")
p4 = ggplot(sharkstudent, aes(x = `BusinessServices`, fill = Deal_Yes)) + geom_bar(position = "fill")
grid.arrange(p1,p2,p3,p4)
```

```{r Group 6 Visualizations}
p1 = ggplot(sharkstudent, aes(x = `LifestyleHome`, fill = Deal_Yes)) + geom_bar(position = "fill")
p2 = ggplot(sharkstudent, aes(x = `SoftwareTech`, fill = Deal_Yes)) + geom_bar(position = "fill")
p3 = ggplot(sharkstudent, aes(x = `ChildrenEducation`, fill = Deal_Yes)) + geom_bar(position = "fill")
p4 = ggplot(sharkstudent, aes(x = `Automotive`, fill = Deal_Yes)) + geom_bar(position = "fill")
grid.arrange(p1,p2,p3,p4)
```

```{r Group 7 Visualizations}
p1 = ggplot(sharkstudent, aes(x = `FashionBeauty`, fill = Deal_Yes)) + geom_bar(position = "fill")
p2 = ggplot(sharkstudent, aes(x = `MediaEntertainment`, fill = Deal_Yes)) + geom_bar(position = "fill")
p3 = ggplot(sharkstudent, aes(x = `FitnessSportsOutdoors`, fill = Deal_Yes)) + geom_bar(position = "fill")
p4 = ggplot(sharkstudent, aes(x = `PetProducts`, fill = Deal_Yes)) + geom_bar(position = "fill")
grid.arrange(p1,p2,p3,p4)
```

```{r Group 8 Visualizations}
p1 = ggplot(sharkstudent, aes(x = Travel, fill = Deal_Yes)) + geom_bar(position = "fill")
p2 = ggplot(sharkstudent, aes(x = `GreenCleanTech`, fill = Deal_Yes)) + geom_bar(position = "fill")
p3 = ggplot(sharkstudent, aes(x = `UncertainOther`, fill = Deal_Yes)) + geom_bar(position = "fill")
grid.arrange(p1,p2,p3)
```

```{r Group 9 Visualizations}
p1 = ggplot(sharkstudent, aes(x = MalePresenter, fill = Deal_Yes)) + geom_bar(position="fill")
p2 = ggplot(sharkstudent, aes(x = FemalePresenter, fill = Deal_Yes)) + geom_bar(position="fill")
p3 = ggplot(sharkstudent, aes(x = MixedGenderPresenters, fill = Deal_Yes)) + geom_bar(position="fill")
grid.arrange(p1,p2,p3, ncol=2)
```

```{r Group 10 Visualizations}
p1 = ggplot(sharkstudent, aes(x = Deal_Yes, y = `Number of Presenters`)) + geom_boxplot()
p2 = ggplot(sharkstudent, aes(x = Deal_Yes, y = AmountRequested)) + geom_boxplot()
p3 = ggplot(sharkstudent, aes(x = Deal_Yes, y = EquityRequested)) + geom_boxplot()
p4 = ggplot(sharkstudent, aes(x = Deal_Yes, y = ImpliedValuationRequested)) + geom_boxplot()
grid.arrange(p1,p2,p3,p4, ncol = 2)
```

```{r Group 11 Visualizations}
p1 = ggplot(sharkstudent, aes(x = BarbaraCorcoran, fill = Deal_Yes)) + geom_bar(position = "fill")
p2 = ggplot(sharkstudent, aes(x = MarkCuban, fill = Deal_Yes)) + geom_bar(position = "fill")
p3 = ggplot(sharkstudent, aes(x = LoriGreiner, fill = Deal_Yes)) + geom_bar(position = "fill")
p4 = ggplot(sharkstudent, aes(x = RobertHerjavec, fill = Deal_Yes)) + geom_bar(position = "fill")
grid.arrange(p1,p2,p3,p4)
```

```{r Group 12 Visualizations}
p1 = ggplot(sharkstudent, aes(x = DaymondJohn, fill = Deal_Yes)) + geom_bar(position = "fill")
p2 = ggplot(sharkstudent, aes(x = KevinOLeary, fill = Deal_Yes)) + geom_bar(position = "fill")
p3 = ggplot(sharkstudent, aes(x = KevinHarrington, fill = Deal_Yes)) + geom_bar(position = "fill")
p4 = ggplot(sharkstudent, aes(x = Guest, fill = Deal_Yes)) + geom_bar(position = "fill")
grid.arrange(p1,p2,p3,p4)
```

#### Final Visualizations______________________________________________________________________

```{r season & Bus}
p1=ggplot(sharkstudent, aes(x = Season, fill = Deal_Yes)) + geom_bar(position = "fill") + theme(axis.text.x = element_text(angle =60)) + labs( y= "Count") + theme(plot.title = element_text(hjust = 0.5,face="bold"))+ scale_fill_discrete(name="Deal Made")     

p2=ggplot(sharkstudent, aes(x = `BusinessServices`, fill = Deal_Yes)) + 
  geom_bar(position = "fill") +
  labs(y = "Count", x = "Product in Business Services", fill = "Deal Made") +
  theme(plot.title = element_text(hjust = 0.5,face="bold"))

grid.arrange(p1,p2,ncol=2)
```

```{r Equity ImpliedVal}
p1=ggplot(sharkstudent, aes(x = Deal_Yes, y = EquityRequested)) +                                # 
  geom_boxplot(outlier.shape = NA) +
  coord_cartesian(ylim = quantile(sharkstudent$EquityRequested, c(0.1, 0.9))) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(y = "Equity Requested %", x = "Deal Made") +
  theme(plot.title = element_text(hjust = 0.5,face="bold"))
grid.arrange(p1,p2)

p2=ggplot(sharkstudent, aes(x = Deal_Yes, y = ImpliedValuationRequested)) + geom_boxplot(outlier.shape = NA)+ 
  coord_cartesian(ylim = quantile(sharkstudent$ImpliedValuationRequested, c(0.1, 0.9))) + scale_y_continuous(labels=scales::dollar_format()) + labs( x="Deal Made", y= "Implied Valuation Requested") + theme(plot.title = element_text(hjust = 0.5,face="bold"))

grid.arrange(p1,p2,ncol=2)
```

```{r Eth1 ChildEd Auto Life}
p1 = ggplot(sharkstudent, aes(x = Eth1, fill = Deal_Yes)) + geom_bar(position = "fill") + 
  geom_bar(position = "fill") +
  labs(y = "Count", x = "Ethnicity of First Presenter", fill = "Deal Made") +
  theme(plot.title = element_text(hjust = 0.5,face="bold")) + theme(axis.text.x =  element_text(angle =60))  

p2 = ggplot(sharkstudent, aes(x = `ChildrenEducation`, fill = Deal_Yes)) + geom_bar(position = "fill")+ 
  geom_bar(position = "fill") +
  labs(y = "Count", x = "Product in Children/Education Category", fill = "Deal Made") +
  theme(plot.title = element_text(hjust = 0.5,face="bold"))

p3 =ggplot(sharkstudent, aes(x = Automotive, fill = Deal_Yes)) + geom_bar(position = "fill") +  
  geom_bar(position = "fill") +
  labs(y = "Count", x = "Product in Automotive Category", fill = "Deal Made") +
  theme(plot.title = element_text(hjust = 0.5,face="bold"))

p4 =ggplot(sharkstudent, aes(x = LifestyleHome, fill = Deal_Yes)) + geom_bar(position = "fill") +  
  geom_bar(position = "fill") +
  labs(y = "Count", x = "Product in Lifestyle/Home", fill = "Deal Made") +
  theme(plot.title = element_text(hjust = 0.5,face="bold"))

grid.arrange(p1,p2,p3,p4,ncol=2)
```


#### Random Forest______________________________________________________________________

```{r create folds}
set.seed(123)
rf_folds = vfold_cv(sharkstudent, v = 5)
```

```{r RF first pass}
set.seed(123)
shark_recipe = recipe(Deal_Yes ~., sharkstudent) %>%
  step_dummy(all_nominal(), -all_outcomes())
  # step_other()
  # step_novel()

rf_model = rand_forest(mtry = tune(), min_n = tune(), trees = 100) %>% #add tuning of mtry and min_n parameters
  #setting trees to 100 here should also speed things up a bit, but more trees might be better
  set_engine("ranger", importance = "permutation") %>% #added importance metric
  set_mode("classification")

shark_wflow = 
  workflow() %>% 
  add_model(rf_model) %>% 
  add_recipe(shark_recipe)

set.seed(123)
rf_res = tune_grid(
  shark_wflow,
  resamples = rf_folds,
  grid = 20 #try 20 different combinations of the random forest tuning parameters
)
```

```{r RFAccPlot}
#Plot for Tuning
rf_res %>%
  collect_metrics() %>%
  filter(.metric == "accuracy") %>%
  select(mean, min_n, mtry) %>%
  pivot_longer(min_n:mtry,
    values_to = "value",
    names_to = "parameter"
  ) %>%
  ggplot(aes(value, mean, color = parameter)) +
  geom_point(show.legend = FALSE) +
  facet_wrap(~parameter, scales = "free_x") +
  labs(x = NULL, y = "Accuracy")

rf_res %>%
  collect_metrics() %>%
  filter(.metric == "accuracy") %>%
  mutate(min_n = factor(min_n)) %>%
  ggplot(aes(mtry, mean, color = min_n)) +
  geom_line(alpha = 0.5, size = 1.5) +
  geom_point() +
  labs(y = "Accuracy")
```

#### Random Forest Tuning______________________________________________________________________

```{r RFTUNE}
#RANDOM FOREST
set.seed(123)
rf_folds = vfold_cv(sharkstudent, v = 5)

set.seed(123)
shark_recipe = recipe(Deal_Yes ~., sharkstudent) %>%
  step_dummy(all_nominal(), -all_outcomes())
  # step_other()
  # step_novel()

rf_model = rand_forest(mtry = tune(), min_n = tune(), trees = 100) %>% #add tuning of mtry and min_n parameters
  #setting trees to 100 here should also speed things up a bit, but more trees might be better
  set_engine("ranger", importance = "permutation") %>% #added importance metric
  set_mode("classification")

shark_wflow = 
  workflow() %>% 
  add_model(rf_model) %>% 
  add_recipe(shark_recipe)


rf_grid = grid_regular(
  mtry(range = c(2, 30)), #these values determined through significant trial and error
  min_n(range = c(15, 25)), #these values determined through significant trial and error
  levels = 5
)

set.seed(123)
rf_res_tuned = tune_grid(
  shark_wflow,
  resamples = rf_folds,
  grid = rf_grid #use the tuning grid
)
```

#### Random Forest Var of Importance______________________________________________________________________

```{r RFVar IMport}
best_rf = select_best(rf_res_tuned, "accuracy")

final_rf = finalize_workflow(
  shark_wflow,
  best_rf
)

final_rf

set.seed(123)
final_rf_fit = fit(final_rf, sharkstudent)

set.seed(123)
final_rf_fit %>% pull_workflow_fit() %>% vip(geom = "point", mapping=aes_string(fill="Variable")) + labs(title="Random Forest Variables of Importance", y="Importance", x="Variable") + theme(plot.title = element_text(hjust = 0.5,face="bold"))
```


